### ISSUE TITLE
Evo-Outfitter component erroneously installs Suppress Snapping package

### ISSUE THREAD

**Issue by Splitwirez** [VanillaCold/Spore-AdvancedCE#2]
Title says it all - enabling the Evo-Outfitter feature erroneously installs the package intended for the Suppress Snapping feature (`Chocice75_AdvCE_NoSnap.package`), rather than its own package (`Chocice75_AdvCE-EvoOutfitter.package`).

(Also, why is there a hyphen in `Chocice75_AdvCE-EvoOutfitter.package`, but an underscore in `Chocice75_AdvCE_NoSnap.package`?)

**Comment by VanillaCold** [comment]
The issue's been fixed now, so I'm closing this.
(as for the hyphen and underscore, not sure tbh. It's probably just me being inconsistent, as always.)
